---
title: "SantanderData"
author: "Oswaldo F. Domejean"
date: "April 14, 2016"
output: word_document
---

Libraries
```{r}

```

Data loading
```{r}
set.seed(1234)
setwd("~/Dropbox/Kaggle/Satander Customer Satisfaction")

train <- read.csv("train.csv")
test  <- read.csv("test.csv")

```


Data transformation
```{r}
##### Removing IDs
train.id <- train$ID
train$ID <- NULL
test.id <- test$ID
test$ID <- NULL

##### Extracting TARGET
train.y <- train$TARGET
train$TARGET <- NULL

##### 0 count per line
count0 <- function(x) {
  return( sum(x == 0) )
}
train$n0 <- apply(train, 1, FUN=count0)
test$n0 <- apply(test, 1, FUN=count0)

##### Removing constant features
cat("\n## Removing the constants features.\n")
for (f in names(train)) {
  if (length(unique(train[[f]])) == 1) {
    cat(f, "is constant in train. We delete it.\n")
    train[[f]] <- NULL
    test[[f]] <- NULL
  }
}

##### Removing identical features
features_pair <- combn(names(train), 2, simplify = F)
toRemove <- c()
for(pair in features_pair) {
  f1 <- pair[1]
  f2 <- pair[2]
  
  if (!(f1 %in% toRemove) & !(f2 %in% toRemove)) {
    if (all(train[[f1]] == train[[f2]])) {
      cat(f1, "and", f2, "are equals.\n")
      toRemove <- c(toRemove, f2)
    }
  }
}

feature.names <- setdiff(names(train), toRemove)

train <- train[, feature.names]
test <- test[, feature.names]

train$ID <- train.id
test$ID <- test.id
train$TARGET <- train.y

```


```{r}
# For train
train$f_div54 <- train$saldo_var6/(train$n0+1)
train$f_sqrt126 <- sqrt(abs(train$num_var37_0+1))
train$f_sqrt102 <- sqrt(abs(train$imp_op_var39_comer_ult1+1))
train$f_div91 <- train$num_var30/(train$saldo_medio_var8_ult3+1)
train$f_div63 <- train$saldo_var44/(train$saldo_var6+1)
train$f_log191 <- log(1+abs(train$num_var30))
train$f_times23 <- train$num_var45_hace3*train$saldo_medio_var13_corto_hace2
train$f_times39 <- train$imp_op_var41_efect_ult1*train$num_var22_hace2
train$f_sqrt116 <- sqrt(abs(train$saldo_var40+1))
train$f_div81 <- train$imp_op_var39_comer_ult3/(train$imp_op_var39_comer_ult3+1)
train$f_times38 <- train$num_var22_hace2*train$imp_op_var39_ult1
train$f_log189 <- log(1+abs(train$imp_op_var41_efect_ult1))
train$f_times22 <- train$saldo_medio_var12_hace2*train$imp_compra_var44_hace3
train$f_log156 <- log(1+abs(train$imp_op_var41_efect_ult3))
train$f_sqrt128 <- sqrt(abs(train$imp_op_var39_ult1+1))
train$f_div79 <- train$num_trasp_var11_ult1/(train$num_var37_med_ult2+1)
train$f_div98 <- train$saldo_medio_var8_hace3/(train$num_var43_emit_ult1+1)
train$f_times14 <- train$num_med_var22_ult3*train$num_var45_ult1
train$f_sqrt147 <- sqrt(abs(train$imp_op_var39_efect_ult3+1))
train$f_sqrt145 <- sqrt(abs(train$imp_compra_var44_hace3+1))
train$f_sqrt131 <- sqrt(abs(train$imp_op_var39_comer_ult3+1))
train$f_times40 <- train$saldo_medio_var13_corto_hace2*train$num_var45_hace3
train$f_div72 <- train$saldo_medio_var12_hace2/(train$imp_compra_var44_hace3+1)
train$f_div87 <- train$imp_op_var39_efect_ult1/(train$num_var22_hace3+1)
train$f_times28 <- train$imp_op_var39_ult1*train$imp_op_var41_efect_ult1
train$f_sqrt114 <- sqrt(abs(train$num_med_var22_ult3+1))
train$f_div94 <- train$num_var5_0/(train$saldo_medio_var8_hace3+1)
train$f_div100 <- train$num_var37_med_ult2/(train$ind_var1_0+1)
train$f_times41 <- train$num_var30*train$saldo_medio_var8_ult3
train$f_sqrt118 <- sqrt(abs(train$num_var45_ult1+1))
train$f_sqrt123 <- sqrt(abs(train$num_var45_hace3+1))
train$f_sqrt120 <- sqrt(abs(train$imp_ent_var16_ult1+1))
train$f_times47 <- train$imp_op_var39_efect_ult3*train$num_trasp_var11_ult1
train$f_sqrt112 <- sqrt(abs(train$num_var22_ult1+1))
train$f_times6 <- train$imp_op_var41_efect_ult3*train$saldo_var40
train$f_div57 <- train$var15/(train$saldo_var12+1)
train$f_log196 <- log(1+abs(train$ind_var1_0))
train$f_sqrt108 <- sqrt(abs(train$saldo_medio_var8_hace2+1))
train$f_times44 <- train$num_var5_0*train$saldo_medio_var8_hace3
train$f_div89 <- train$imp_op_var41_efect_ult1/(train$num_var22_hace2+1)
train$f_div96 <- train$ind_var1_0/(train$saldo_medio_var5_hace2+1)
train$f_sqrt101 <- sqrt(abs(train$imp_trasp_var17_in_hace3+1))
train$f_div90 <- train$saldo_medio_var13_corto_hace2/(train$num_var45_hace3+1)
train$f_log163 <- log(1+abs(train$saldo_var44))
train$f_sqrt103 <- sqrt(abs(train$n0+1))
train$f_div76 <- train$num_var37_0/(train$num_meses_var5_ult3+1)
train$f_sqrt104 <- sqrt(abs(train$saldo_var6+1))
train$f_log173 <- log(1+abs(train$num_var45_hace3))
train$f_div75 <- train$ind_var8/(train$imp_trans_var37_ult1+1)
train$f_sqrt111 <- sqrt(abs(train$saldo_medio_var5_hace3+1))
train$f_log162 <- log(1+abs(train$num_var22_ult1))
train$f_times26 <- train$num_var37_0*train$num_meses_var5_ult3
train$f_div85 <- train$num_var43_emit_ult1/(train$num_op_var41_efect_ult3+1)
train$f_log155 <- log(1+abs(train$imp_op_var41_comer_ult3))
train$f_times1 <- train$imp_trasp_var17_in_hace3*train$imp_ent_var16_ult1
train$f_log172 <- log(1+abs(train$saldo_medio_var12_hace2))
train$f_times43 <- train$saldo_medio_var8_ult1*train$imp_op_var39_efect_ult3
train$f_log151 <- log(1+abs(train$imp_trasp_var17_in_hace3))
train$f_times3 <- train$n0*train$saldo_medio_var5_ult1
train$f_log159 <- log(1+abs(train$saldo_medio_var5_ult3))
train$f_sqrt136 <- sqrt(abs(train$saldo_medio_var5_hace2+1))
train$f_times16 <- train$saldo_var40*train$saldo_var44
train$f_times50 <- train$num_var37_med_ult2*train$ind_var1_0
train$f_div99 <- train$saldo_medio_var8_ult3/(train$imp_op_var41_ult1+1)
train$f_div68 <- train$num_var45_ult1/(train$num_var22_ult1+1)
train$f_sqrt139 <- sqrt(abs(train$imp_op_var41_efect_ult1+1))
train$f_times4 <- train$saldo_var6*train$n0
train$f_div58 <- train$saldo_medio_var8_hace2/(train$num_med_var22_ult3+1)
train$f_log183 <- log(1+abs(train$imp_trans_var37_ult1))
train$f_log199 <- log(1+abs(train$saldo_medio_var8_ult3))
train$f_sqrt141 <- sqrt(abs(train$num_var30+1))
train$f_sqrt119 <- sqrt(abs(train$saldo_var12+1))
train$f_div83 <- train$imp_trans_var37_ult1/(train$imp_op_var39_efect_ult1+1)
train$f_div62 <- train$num_var22_ult1/(train$imp_op_var39_comer_ult1+1)
train$f_sqrt146 <- sqrt(abs(train$ind_var1_0+1))
train$f_times27 <- train$num_meses_var44_ult3*train$num_meses_var44_ult3
train$f_sqrt133 <- sqrt(abs(train$imp_trans_var37_ult1+1))
train$f_log187 <- log(1+abs(train$imp_op_var39_efect_ult1))
train$f_div77 <- train$num_meses_var44_ult3/(train$num_meses_var44_ult3+1)
train$f_div88 <- train$num_var22_hace2/(train$imp_op_var39_ult1+1)
train$f_sqrt135 <- sqrt(abs(train$num_var43_emit_ult1+1))
train$f_log157 <- log(1+abs(train$var15))
train$f_log160 <- log(1+abs(train$saldo_var31))
train$f_times20 <- train$imp_ent_var16_ult1*train$saldo_var31
train$f_times31 <- train$imp_op_var39_comer_ult3*train$imp_op_var39_comer_ult3
train$f_div92 <- train$num_var22_hace3/(train$ind_var8+1)
train$f_times45 <- train$imp_compra_var44_hace3*train$num_var5_0
train$f_times18 <- train$num_var45_ult1*train$num_var22_ult1
train$f_log152 <- log(1+abs(train$imp_op_var39_comer_ult1))
train$f_div69 <- train$saldo_var12/(train$num_var22_ult3+1)
train$f_sqrt143 <- sqrt(abs(train$saldo_medio_var8_ult1+1))
train$f_sqrt148 <- sqrt(abs(train$saldo_medio_var8_hace3+1))
train$f_sqrt125 <- sqrt(abs(train$ind_var8+1))
train$f_sqrt150 <- sqrt(abs(train$num_var37_med_ult2+1))
train$f_times9 <- train$saldo_medio_var5_ult3*train$imp_trasp_var17_in_hace3
train$f_log186 <- log(1+abs(train$saldo_medio_var5_hace2))
train$f_div70 <- train$imp_ent_var16_ult1/(train$saldo_var31+1)
train$f_sqrt142 <- sqrt(abs(train$num_var22_hace3+1))
train$f_log188 <- log(1+abs(train$num_var22_hace2))
train$f_times19 <- train$saldo_var12*train$num_var22_ult3
train$f_log193 <- log(1+abs(train$saldo_medio_var8_ult1))
train$f_log153 <- log(1+abs(train$n0))
train$f_log180 <- log(1+abs(train$imp_sal_var16_ult1))
train$f_log200 <- log(1+abs(train$num_var37_med_ult2))
train$f_sqrt115 <- sqrt(abs(train$num_var22_ult3+1))
train$f_times17 <- train$saldo_medio_var5_ult1*train$saldo_medio_var5_ult3
train$f_log158 <- log(1+abs(train$saldo_medio_var8_hace2))
train$f_div74 <- train$imp_op_var41_ult1/(train$saldo_medio_var8_ult1+1)
train$f_times7 <- train$var15*train$saldo_var12
train$f_times15 <- train$num_var22_ult3*train$saldo_medio_var5_hace3
train$f_log166 <- log(1+abs(train$saldo_var40))
train$f_log174 <- log(1+abs(train$imp_op_var41_ult1))
train$f_log171 <- log(1+abs(train$num_op_var41_efect_ult3))
train$f_log198 <- log(1+abs(train$saldo_medio_var8_hace3))
train$f_div73 <- train$num_var45_hace3/(train$saldo_medio_var13_corto_hace2+1)
train$f_log169 <- log(1+abs(train$saldo_var12))
train$f_times37 <- train$imp_op_var39_efect_ult1*train$num_var22_hace3
train$f_sqrt121 <- sqrt(abs(train$num_op_var41_efect_ult3+1))
train$f_log194 <- log(1+abs(train$num_var5_0))
train$f_log190 <- log(1+abs(train$saldo_medio_var13_corto_hace2))
train$f_div95 <- train$imp_compra_var44_hace3/(train$num_var5_0+1)
train$f_log168 <- log(1+abs(train$num_var45_ult1))
train$f_log178 <- log(1+abs(train$imp_op_var39_ult1))
train$f_times49 <- train$saldo_medio_var8_ult3*train$imp_op_var41_ult1
train$f_div80 <- train$imp_sal_var16_ult1/(train$num_var37_0+1)
train$f_sqrt127 <- sqrt(abs(train$num_meses_var44_ult3+1))
train$f_times29 <- train$num_trasp_var11_ult1*train$num_var37_med_ult2
train$f_log175 <- log(1+abs(train$ind_var8))
train$f_div93 <- train$saldo_medio_var8_ult1/(train$imp_op_var39_efect_ult3+1)
train$f_times35 <- train$num_var43_emit_ult1*train$num_op_var41_efect_ult3
train$f_log179 <- log(1+abs(train$num_trasp_var11_ult1))
train$f_div97 <- train$imp_op_var39_efect_ult3/(train$num_trasp_var11_ult1+1)
train$f_log197 <- log(1+abs(train$imp_op_var39_efect_ult3))
train$f_log161 <- log(1+abs(train$saldo_medio_var5_hace3))
train$f_div82 <- train$imp_op_var40_comer_ult1/(train$imp_sal_var16_ult1+1)
train$f_times13 <- train$saldo_var44*train$saldo_var6
train$f_div66 <- train$saldo_var40/(train$saldo_var44+1)
train$f_div65 <- train$num_var22_ult3/(train$saldo_medio_var5_hace3+1)
train$f_sqrt130 <- sqrt(abs(train$imp_sal_var16_ult1+1))
train$f_times46 <- train$ind_var1_0*train$saldo_medio_var5_hace2
train$f_log167 <- log(1+abs(train$saldo_medio_var5_ult1))
train$f_sqrt109 <- sqrt(abs(train$saldo_medio_var5_ult3+1))
train$f_log170 <- log(1+abs(train$imp_ent_var16_ult1))
train$f_div84 <- train$num_meses_var5_ult3/(train$saldo_medio_var12_hace2+1)
train$f_div56 <- train$imp_op_var41_efect_ult3/(train$saldo_var40+1)
train$f_div61 <- train$saldo_medio_var5_hace3/(train$imp_op_var41_efect_ult3+1)
train$f_sqrt113 <- sqrt(abs(train$saldo_var44+1))
train$f_sqrt137 <- sqrt(abs(train$imp_op_var39_efect_ult1+1))
train$f_div59 <- train$saldo_medio_var5_ult3/(train$imp_trasp_var17_in_hace3+1)
train$f_times30 <- train$imp_sal_var16_ult1*train$num_var37_0
train$f_log184 <- log(1+abs(train$num_meses_var5_ult3))
train$f_div53 <- train$n0/(train$saldo_medio_var5_ult1+1)
train$f_sqrt134 <- sqrt(abs(train$num_meses_var5_ult3+1))
train$f_div71 <- train$num_op_var41_efect_ult3/(train$num_var30+1)
train$f_sqrt144 <- sqrt(abs(train$num_var5_0+1))
train$f_times24 <- train$imp_op_var41_ult1*train$saldo_medio_var8_ult1
train$f_div55 <- train$imp_op_var41_comer_ult3/(train$imp_op_var41_comer_ult3+1)
train$f_log154 <- log(1+abs(train$saldo_var6))
train$f_div67 <- train$saldo_medio_var5_ult1/(train$saldo_medio_var5_ult3+1)
train$f_log176 <- log(1+abs(train$num_var37_0))
train$f_log192 <- log(1+abs(train$num_var22_hace3))
train$f_sqrt117 <- sqrt(abs(train$saldo_medio_var5_ult1+1))
train$f_times5 <- train$imp_op_var41_comer_ult3*train$imp_op_var41_comer_ult3
train$f_sqrt107 <- sqrt(abs(train$var15+1))
train$f_sqrt149 <- sqrt(abs(train$saldo_medio_var8_ult3+1))
train$f_log165 <- log(1+abs(train$num_var22_ult3))
train$f_log177 <- log(1+abs(train$num_meses_var44_ult3))
train$f_times2 <- train$imp_op_var39_comer_ult1*train$saldo_medio_var8_hace2
train$f_times33 <- train$imp_trans_var37_ult1*train$imp_op_var39_efect_ult1
train$f_times10 <- train$saldo_var31*train$var15
train$f_div51 <- train$imp_trasp_var17_in_hace3/(train$imp_ent_var16_ult1+1)
train$f_div64 <- train$num_med_var22_ult3/(train$num_var45_ult1+1)
train$f_log164 <- log(1+abs(train$num_med_var22_ult3))
train$f_sqrt138 <- sqrt(abs(train$num_var22_hace2+1))
train$f_times8 <- train$saldo_medio_var8_hace2*train$num_med_var22_ult3
train$f_div86 <- train$saldo_medio_var5_hace2/(train$imp_op_var40_comer_ult1+1)
train$f_times12 <- train$num_var22_ult1*train$imp_op_var39_comer_ult1
train$f_times32 <- train$imp_op_var40_comer_ult1*train$imp_sal_var16_ult1
train$f_times11 <- train$saldo_medio_var5_hace3*train$imp_op_var41_efect_ult3
train$f_times25 <- train$ind_var8*train$imp_trans_var37_ult1
train$f_div52 <- train$imp_op_var39_comer_ult1/(train$saldo_medio_var8_hace2+1)
train$f_times21 <- train$num_op_var41_efect_ult3*train$num_var30
train$f_sqrt105 <- sqrt(abs(train$imp_op_var41_comer_ult3+1))
train$f_log185 <- log(1+abs(train$num_var43_emit_ult1))
train$f_log181 <- log(1+abs(train$imp_op_var39_comer_ult3))
train$f_sqrt132 <- sqrt(abs(train$imp_op_var40_comer_ult1+1))
train$f_sqrt140 <- sqrt(abs(train$saldo_medio_var13_corto_hace2+1))
train$f_sqrt122 <- sqrt(abs(train$saldo_medio_var12_hace2+1))
train$f_times48 <- train$saldo_medio_var8_hace3*train$num_var43_emit_ult1
train$f_div60 <- train$saldo_var31/(train$var15+1)
train$f_times36 <- train$saldo_medio_var5_hace2*train$imp_op_var40_comer_ult1
train$f_sqrt106 <- sqrt(abs(train$imp_op_var41_efect_ult3+1))
train$f_log182 <- log(1+abs(train$imp_op_var40_comer_ult1))
train$f_times34 <- train$num_meses_var5_ult3*train$saldo_medio_var12_hace2
train$f_sqrt124 <- sqrt(abs(train$imp_op_var41_ult1+1))
train$f_div78 <- train$imp_op_var39_ult1/(train$imp_op_var41_efect_ult1+1)
train$f_times42 <- train$num_var22_hace3*train$ind_var8
train$f_log195 <- log(1+abs(train$imp_compra_var44_hace3))
train$f_sqrt129 <- sqrt(abs(train$num_trasp_var11_ult1+1))
train$f_sqrt110 <- sqrt(abs(train$saldo_var31+1))

# for test
test$f_div54 <- test$saldo_var6/(test$n0+1)
test$f_sqrt126 <- sqrt(abs(test$num_var37_0+1))
test$f_sqrt102 <- sqrt(abs(test$imp_op_var39_comer_ult1+1))
test$f_div91 <- test$num_var30/(test$saldo_medio_var8_ult3+1)
test$f_div63 <- test$saldo_var44/(test$saldo_var6+1)
test$f_log191 <- log(1+abs(test$num_var30))
test$f_times23 <- test$num_var45_hace3*test$saldo_medio_var13_corto_hace2
test$f_times39 <- test$imp_op_var41_efect_ult1*test$num_var22_hace2
test$f_sqrt116 <- sqrt(abs(test$saldo_var40+1))
test$f_div81 <- test$imp_op_var39_comer_ult3/(test$imp_op_var39_comer_ult3+1)
test$f_times38 <- test$num_var22_hace2*test$imp_op_var39_ult1
test$f_log189 <- log(1+abs(test$imp_op_var41_efect_ult1))
test$f_times22 <- test$saldo_medio_var12_hace2*test$imp_compra_var44_hace3
test$f_log156 <- log(1+abs(test$imp_op_var41_efect_ult3))
test$f_sqrt128 <- sqrt(abs(test$imp_op_var39_ult1+1))
test$f_div79 <- test$num_trasp_var11_ult1/(test$num_var37_med_ult2+1)
test$f_div98 <- test$saldo_medio_var8_hace3/(test$num_var43_emit_ult1+1)
test$f_times14 <- test$num_med_var22_ult3*test$num_var45_ult1
test$f_sqrt147 <- sqrt(abs(test$imp_op_var39_efect_ult3+1))
test$f_sqrt145 <- sqrt(abs(test$imp_compra_var44_hace3+1))
test$f_sqrt131 <- sqrt(abs(test$imp_op_var39_comer_ult3+1))
test$f_times40 <- test$saldo_medio_var13_corto_hace2*test$num_var45_hace3
test$f_div72 <- test$saldo_medio_var12_hace2/(test$imp_compra_var44_hace3+1)
test$f_div87 <- test$imp_op_var39_efect_ult1/(test$num_var22_hace3+1)
test$f_times28 <- test$imp_op_var39_ult1*test$imp_op_var41_efect_ult1
test$f_sqrt114 <- sqrt(abs(test$num_med_var22_ult3+1))
test$f_div94 <- test$num_var5_0/(test$saldo_medio_var8_hace3+1)
test$f_div100 <- test$num_var37_med_ult2/(test$ind_var1_0+1)
test$f_times41 <- test$num_var30*test$saldo_medio_var8_ult3
test$f_sqrt118 <- sqrt(abs(test$num_var45_ult1+1))
test$f_sqrt123 <- sqrt(abs(test$num_var45_hace3+1))
test$f_sqrt120 <- sqrt(abs(test$imp_ent_var16_ult1+1))
test$f_times47 <- test$imp_op_var39_efect_ult3*test$num_trasp_var11_ult1
test$f_sqrt112 <- sqrt(abs(test$num_var22_ult1+1))
test$f_times6 <- test$imp_op_var41_efect_ult3*test$saldo_var40
test$f_div57 <- test$var15/(test$saldo_var12+1)
test$f_log196 <- log(1+abs(test$ind_var1_0))
test$f_sqrt108 <- sqrt(abs(test$saldo_medio_var8_hace2+1))
test$f_times44 <- test$num_var5_0*test$saldo_medio_var8_hace3
test$f_div89 <- test$imp_op_var41_efect_ult1/(test$num_var22_hace2+1)
test$f_div96 <- test$ind_var1_0/(test$saldo_medio_var5_hace2+1)
test$f_sqrt101 <- sqrt(abs(test$imp_trasp_var17_in_hace3+1))
test$f_div90 <- test$saldo_medio_var13_corto_hace2/(test$num_var45_hace3+1)
test$f_log163 <- log(1+abs(test$saldo_var44))
test$f_sqrt103 <- sqrt(abs(test$n0+1))
test$f_div76 <- test$num_var37_0/(test$num_meses_var5_ult3+1)
test$f_sqrt104 <- sqrt(abs(test$saldo_var6+1))
test$f_log173 <- log(1+abs(test$num_var45_hace3))
test$f_div75 <- test$ind_var8/(test$imp_trans_var37_ult1+1)
test$f_sqrt111 <- sqrt(abs(test$saldo_medio_var5_hace3+1))
test$f_log162 <- log(1+abs(test$num_var22_ult1))
test$f_times26 <- test$num_var37_0*test$num_meses_var5_ult3
test$f_div85 <- test$num_var43_emit_ult1/(test$num_op_var41_efect_ult3+1)
test$f_log155 <- log(1+abs(test$imp_op_var41_comer_ult3))
test$f_times1 <- test$imp_trasp_var17_in_hace3*test$imp_ent_var16_ult1
test$f_log172 <- log(1+abs(test$saldo_medio_var12_hace2))
test$f_times43 <- test$saldo_medio_var8_ult1*test$imp_op_var39_efect_ult3
test$f_log151 <- log(1+abs(test$imp_trasp_var17_in_hace3))
test$f_times3 <- test$n0*test$saldo_medio_var5_ult1
test$f_log159 <- log(1+abs(test$saldo_medio_var5_ult3))
test$f_sqrt136 <- sqrt(abs(test$saldo_medio_var5_hace2+1))
test$f_times16 <- test$saldo_var40*test$saldo_var44
test$f_times50 <- test$num_var37_med_ult2*test$ind_var1_0
test$f_div99 <- test$saldo_medio_var8_ult3/(test$imp_op_var41_ult1+1)
test$f_div68 <- test$num_var45_ult1/(test$num_var22_ult1+1)
test$f_sqrt139 <- sqrt(abs(test$imp_op_var41_efect_ult1+1))
test$f_times4 <- test$saldo_var6*test$n0
test$f_div58 <- test$saldo_medio_var8_hace2/(test$num_med_var22_ult3+1)
test$f_log183 <- log(1+abs(test$imp_trans_var37_ult1))
test$f_log199 <- log(1+abs(test$saldo_medio_var8_ult3))
test$f_sqrt141 <- sqrt(abs(test$num_var30+1))
test$f_sqrt119 <- sqrt(abs(test$saldo_var12+1))
test$f_div83 <- test$imp_trans_var37_ult1/(test$imp_op_var39_efect_ult1+1)
test$f_div62 <- test$num_var22_ult1/(test$imp_op_var39_comer_ult1+1)
test$f_sqrt146 <- sqrt(abs(test$ind_var1_0+1))
test$f_times27 <- test$num_meses_var44_ult3*test$num_meses_var44_ult3
test$f_sqrt133 <- sqrt(abs(test$imp_trans_var37_ult1+1))
test$f_log187 <- log(1+abs(test$imp_op_var39_efect_ult1))
test$f_div77 <- test$num_meses_var44_ult3/(test$num_meses_var44_ult3+1)
test$f_div88 <- test$num_var22_hace2/(test$imp_op_var39_ult1+1)
test$f_sqrt135 <- sqrt(abs(test$num_var43_emit_ult1+1))
test$f_log157 <- log(1+abs(test$var15))
test$f_log160 <- log(1+abs(test$saldo_var31))
test$f_times20 <- test$imp_ent_var16_ult1*test$saldo_var31
test$f_times31 <- test$imp_op_var39_comer_ult3*test$imp_op_var39_comer_ult3
test$f_div92 <- test$num_var22_hace3/(test$ind_var8+1)
test$f_times45 <- test$imp_compra_var44_hace3*test$num_var5_0
test$f_times18 <- test$num_var45_ult1*test$num_var22_ult1
test$f_log152 <- log(1+abs(test$imp_op_var39_comer_ult1))
test$f_div69 <- test$saldo_var12/(test$num_var22_ult3+1)
test$f_sqrt143 <- sqrt(abs(test$saldo_medio_var8_ult1+1))
test$f_sqrt148 <- sqrt(abs(test$saldo_medio_var8_hace3+1))
test$f_sqrt125 <- sqrt(abs(test$ind_var8+1))
test$f_sqrt150 <- sqrt(abs(test$num_var37_med_ult2+1))
test$f_times9 <- test$saldo_medio_var5_ult3*test$imp_trasp_var17_in_hace3
test$f_log186 <- log(1+abs(test$saldo_medio_var5_hace2))
test$f_div70 <- test$imp_ent_var16_ult1/(test$saldo_var31+1)
test$f_sqrt142 <- sqrt(abs(test$num_var22_hace3+1))
test$f_log188 <- log(1+abs(test$num_var22_hace2))
test$f_times19 <- test$saldo_var12*test$num_var22_ult3
test$f_log193 <- log(1+abs(test$saldo_medio_var8_ult1))
test$f_log153 <- log(1+abs(test$n0))
test$f_log180 <- log(1+abs(test$imp_sal_var16_ult1))
test$f_log200 <- log(1+abs(test$num_var37_med_ult2))
test$f_sqrt115 <- sqrt(abs(test$num_var22_ult3+1))
test$f_times17 <- test$saldo_medio_var5_ult1*test$saldo_medio_var5_ult3
test$f_log158 <- log(1+abs(test$saldo_medio_var8_hace2))
test$f_div74 <- test$imp_op_var41_ult1/(test$saldo_medio_var8_ult1+1)
test$f_times7 <- test$var15*test$saldo_var12
test$f_times15 <- test$num_var22_ult3*test$saldo_medio_var5_hace3
test$f_log166 <- log(1+abs(test$saldo_var40))
test$f_log174 <- log(1+abs(test$imp_op_var41_ult1))
test$f_log171 <- log(1+abs(test$num_op_var41_efect_ult3))
test$f_log198 <- log(1+abs(test$saldo_medio_var8_hace3))
test$f_div73 <- test$num_var45_hace3/(test$saldo_medio_var13_corto_hace2+1)
test$f_log169 <- log(1+abs(test$saldo_var12))
test$f_times37 <- test$imp_op_var39_efect_ult1*test$num_var22_hace3
test$f_sqrt121 <- sqrt(abs(test$num_op_var41_efect_ult3+1))
test$f_log194 <- log(1+abs(test$num_var5_0))
test$f_log190 <- log(1+abs(test$saldo_medio_var13_corto_hace2))
test$f_div95 <- test$imp_compra_var44_hace3/(test$num_var5_0+1)
test$f_log168 <- log(1+abs(test$num_var45_ult1))
test$f_log178 <- log(1+abs(test$imp_op_var39_ult1))
test$f_times49 <- test$saldo_medio_var8_ult3*test$imp_op_var41_ult1
test$f_div80 <- test$imp_sal_var16_ult1/(test$num_var37_0+1)
test$f_sqrt127 <- sqrt(abs(test$num_meses_var44_ult3+1))
test$f_times29 <- test$num_trasp_var11_ult1*test$num_var37_med_ult2
test$f_log175 <- log(1+abs(test$ind_var8))
test$f_div93 <- test$saldo_medio_var8_ult1/(test$imp_op_var39_efect_ult3+1)
test$f_times35 <- test$num_var43_emit_ult1*test$num_op_var41_efect_ult3
test$f_log179 <- log(1+abs(test$num_trasp_var11_ult1))
test$f_div97 <- test$imp_op_var39_efect_ult3/(test$num_trasp_var11_ult1+1)
test$f_log197 <- log(1+abs(test$imp_op_var39_efect_ult3))
test$f_log161 <- log(1+abs(test$saldo_medio_var5_hace3))
test$f_div82 <- test$imp_op_var40_comer_ult1/(test$imp_sal_var16_ult1+1)
test$f_times13 <- test$saldo_var44*test$saldo_var6
test$f_div66 <- test$saldo_var40/(test$saldo_var44+1)
test$f_div65 <- test$num_var22_ult3/(test$saldo_medio_var5_hace3+1)
test$f_sqrt130 <- sqrt(abs(test$imp_sal_var16_ult1+1))
test$f_times46 <- test$ind_var1_0*test$saldo_medio_var5_hace2
test$f_log167 <- log(1+abs(test$saldo_medio_var5_ult1))
test$f_sqrt109 <- sqrt(abs(test$saldo_medio_var5_ult3+1))
test$f_log170 <- log(1+abs(test$imp_ent_var16_ult1))
test$f_div84 <- test$num_meses_var5_ult3/(test$saldo_medio_var12_hace2+1)
test$f_div56 <- test$imp_op_var41_efect_ult3/(test$saldo_var40+1)
test$f_div61 <- test$saldo_medio_var5_hace3/(test$imp_op_var41_efect_ult3+1)
test$f_sqrt113 <- sqrt(abs(test$saldo_var44+1))
test$f_sqrt137 <- sqrt(abs(test$imp_op_var39_efect_ult1+1))
test$f_div59 <- test$saldo_medio_var5_ult3/(test$imp_trasp_var17_in_hace3+1)
test$f_times30 <- test$imp_sal_var16_ult1*test$num_var37_0
test$f_log184 <- log(1+abs(test$num_meses_var5_ult3))
test$f_div53 <- test$n0/(test$saldo_medio_var5_ult1+1)
test$f_sqrt134 <- sqrt(abs(test$num_meses_var5_ult3+1))
test$f_div71 <- test$num_op_var41_efect_ult3/(test$num_var30+1)
test$f_sqrt144 <- sqrt(abs(test$num_var5_0+1))
test$f_times24 <- test$imp_op_var41_ult1*test$saldo_medio_var8_ult1
test$f_div55 <- test$imp_op_var41_comer_ult3/(test$imp_op_var41_comer_ult3+1)
test$f_log154 <- log(1+abs(test$saldo_var6))
test$f_div67 <- test$saldo_medio_var5_ult1/(test$saldo_medio_var5_ult3+1)
test$f_log176 <- log(1+abs(test$num_var37_0))
test$f_log192 <- log(1+abs(test$num_var22_hace3))
test$f_sqrt117 <- sqrt(abs(test$saldo_medio_var5_ult1+1))
test$f_times5 <- test$imp_op_var41_comer_ult3*test$imp_op_var41_comer_ult3
test$f_sqrt107 <- sqrt(abs(test$var15+1))
test$f_sqrt149 <- sqrt(abs(test$saldo_medio_var8_ult3+1))
test$f_log165 <- log(1+abs(test$num_var22_ult3))
test$f_log177 <- log(1+abs(test$num_meses_var44_ult3))
test$f_times2 <- test$imp_op_var39_comer_ult1*test$saldo_medio_var8_hace2
test$f_times33 <- test$imp_trans_var37_ult1*test$imp_op_var39_efect_ult1
test$f_times10 <- test$saldo_var31*test$var15
test$f_div51 <- test$imp_trasp_var17_in_hace3/(test$imp_ent_var16_ult1+1)
test$f_div64 <- test$num_med_var22_ult3/(test$num_var45_ult1+1)
test$f_log164 <- log(1+abs(test$num_med_var22_ult3))
test$f_sqrt138 <- sqrt(abs(test$num_var22_hace2+1))
test$f_times8 <- test$saldo_medio_var8_hace2*test$num_med_var22_ult3
test$f_div86 <- test$saldo_medio_var5_hace2/(test$imp_op_var40_comer_ult1+1)
test$f_times12 <- test$num_var22_ult1*test$imp_op_var39_comer_ult1
test$f_times32 <- test$imp_op_var40_comer_ult1*test$imp_sal_var16_ult1
test$f_times11 <- test$saldo_medio_var5_hace3*test$imp_op_var41_efect_ult3
test$f_times25 <- test$ind_var8*test$imp_trans_var37_ult1
test$f_div52 <- test$imp_op_var39_comer_ult1/(test$saldo_medio_var8_hace2+1)
test$f_times21 <- test$num_op_var41_efect_ult3*test$num_var30
test$f_sqrt105 <- sqrt(abs(test$imp_op_var41_comer_ult3+1))
test$f_log185 <- log(1+abs(test$num_var43_emit_ult1))
test$f_log181 <- log(1+abs(test$imp_op_var39_comer_ult3))
test$f_sqrt132 <- sqrt(abs(test$imp_op_var40_comer_ult1+1))
test$f_sqrt140 <- sqrt(abs(test$saldo_medio_var13_corto_hace2+1))
test$f_sqrt122 <- sqrt(abs(test$saldo_medio_var12_hace2+1))
test$f_times48 <- test$saldo_medio_var8_hace3*test$num_var43_emit_ult1
test$f_div60 <- test$saldo_var31/(test$var15+1)
test$f_times36 <- test$saldo_medio_var5_hace2*test$imp_op_var40_comer_ult1
test$f_sqrt106 <- sqrt(abs(test$imp_op_var41_efect_ult3+1))
test$f_log182 <- log(1+abs(test$imp_op_var40_comer_ult1))
test$f_times34 <- test$num_meses_var5_ult3*test$saldo_medio_var12_hace2
test$f_sqrt124 <- sqrt(abs(test$imp_op_var41_ult1+1))
test$f_div78 <- test$imp_op_var39_ult1/(test$imp_op_var41_efect_ult1+1)
test$f_times42 <- test$num_var22_hace3*test$ind_var8
test$f_log195 <- log(1+abs(test$imp_compra_var44_hace3))
test$f_sqrt129 <- sqrt(abs(test$num_trasp_var11_ult1+1))
test$f_sqrt110 <- sqrt(abs(test$saldo_var31+1))


```

